# Welcome to Socket!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: socket
email: pingðŸ“¯ssocket.de
description: >- # this means to ignore newlines until "baseurl:"
  socket.de | Clouds | Systems | Networks
baseurl: ""
default_language: "en"
url: https://socket.de
twitter_username:
github_username: codecap
permalink:
#theme: socket

plugins:
  - jekyll-redirect-from

# Value to use in menu per language
menu:
  services:
    en: "Services"
    de: "Services"
  about:
    en: "About"
    de: "Wir"
  imprint:
    en: "Imprint"
    de: "Impressum"
  vna:
    en: "Profile"
    de: "Profile"
# Path to the translated page
t:
  services:
    en: "/service"
    de: "/services"
  about:
    en: "/about"
    de: "/wir"
  imprint:
    en: "/imprint"
    de: "/impressum"
  vna:
    en: "/profile"
    de: "/vna"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - node_modules
  - package.json
  - package-lock.json
  - gulpfile.js
  - npm-shrinkwrap.json
  - socket.gemspec
  - README.md
  - LICENSE.txt
